# Variable 'doc_repo_location' was defined in the Variables tab
# Variable 'params' was defined in the Variables tab
# Variable 'SkipUpdateTocs' was defined in the Variables tab
# Variable 'tools_repo_location' was defined in the Variables tab
# Variable 'tools_repo_SHA' was defined in the Variables tab
# Variable 'ReferenceLanguage' was defined in the Variables tab
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - metadata/legacy
    - ci-configs/packages-legacy.json
    
resources:
  repositories:
    - repository: ReferenceAutomation
      type: git
      name: Content CI/ReferenceAutomation
      ref: refs/heads/sai-testjumppipeline

extends:
  template: nodejs/pipeline-yaml/azure-node-combined-ci-archive.yml@ReferenceAutomation