# Variable 'doc_repo_location' was defined in the Variables tab
# Variable 'params' was defined in the Variables tab
# Variable 'SkipUpdateTocs' was defined in the Variables tab
# Variable 'tools_repo_location' was defined in the Variables tab
# Variable 'tools_repo_SHA' was defined in the Variables tab
# Variable 'ReferenceLanguage' was defined in the Variables tab
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - metadata/legacy
    - ci-configs/packages-legacy.json
    
resources:
  repositories:
    - repository: ReferenceAutomation
      type: git
      name: Content CI/ReferenceAutomation
      ref: refs/heads/master

jobs:
- job: Phase_1
  displayName: Phase 1
  timeoutInMinutes: 240
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-latest
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - script: set
    displayName: List environment variables
  - task: PowerShell@2
    displayName: Set Variables
    inputs:
      targetType: inline
      script: |
        $azureCommonFilePath = Join-Path $(Build.SourcesDirectory) nodejs Shared AzureCommon.ps1
        Write-Host "##vso[task.setvariable variable=azureCommonFilePath]$azureCommonFilePath"
      pwsh: true
  - task: NodeTool@0
    displayName: Use Node 20.12.1
    inputs:
      versionSpec: 20.12.1
      checkLatest: true
  - task: npmAuthenticate@0
    displayName: npm Authenticate
    inputs:
      workingFile: $(Build.Repository.LocalPath)nodejs/JavaScriptTypeScript/.npmrc
  - task: CmdLine@2
    displayName: Build source code
    inputs:
      script: |
        npm install
        npm run build
      workingDirectory: $(Build.Repository.LocalPath)nodejs/JavaScriptTypeScript
  - task: PowerShell@2
    displayName: Install type2docfx
    inputs:
      filePath: $(Build.Repository.LocalPath)nodejs/Shared/InstallType2docfx.ps1
  - task: AzureCLI@2
    displayName: FederatedIdentity for ADO
    inputs:
      azureSubscription: 631c8994-cbef-48c4-b7f2-d97e8a790c29 # ReferenceAutomationPipeline
      scriptType: pscore
      scriptPath: $(Build.Repository.LocalPath)common/FederatedIdentity.ps1
  - task: AzurePowerShell@5
    displayName: git pull
    inputs:
      azureSubscription: 631c8994-cbef-48c4-b7f2-d97e8a790c29 # ReferenceAutomationPipeline
      ScriptPath: $(Build.Repository.LocalPath)common/CI.pull.ps1
      ScriptArguments: " -paramsJson '$(params)' -vstsTokenBase64 '$(vstsTokenBase64)'"
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion
  - task: PowerShell@2
    name: GenerateLegacyDocumentation
    displayName: Generate Legacy Documentation
    enabled: true
    inputs:
      targetType: inline
      script: |
        . $(azureCommonFilePath)
        GenerateDocumentationByJsonFile 'packages-legacy.json'
      pwsh: true
  - task: UsePythonVersion@0
    displayName: Use Python 3.9
    condition: and(succeeded(), ne(variables['SkipUpdateTocs'], 'true'))
    inputs:
      versionSpec: 3.9
  - task: PipAuthenticate@1
    displayName: Pip Authenticate
    inputs:
      artifactFeeds: Content CI/Content_CI_PublicPackages
  - task: PowerShell@2
    displayName: Install tooling repo and tooling pre-reqs
    condition: and(succeeded(), ne(variables['SkipUpdateTocs'], 'true'))
    inputs:
      targetType: inline
      script: |
        git clone https://github.com/Azure/azure-sdk-tools $(tools_repo_location)
        cd $(tools_repo_location)
        git checkout $(tools_repo_SHA)
        $requirementsPath = Join-Path $(tools_repo_location) 'scripts' 'python' 'docs-automation' 'requirements.txt'
        pip install -r $requirementsPath
      pwsh: true
  - task: PowerShell@2
    name: UpdateLegacyToCs
    displayName: Update ToCs(legacy)
    condition: and(succeeded(), ne(variables['SkipUpdateTocs'], 'true'))
    enabled: true
    inputs:
      targetType: inline
      script: |
        . $(azureCommonFilePath)
        # handle legacy
        UpdateTocsByMoniker 'legacy'
      pwsh: true
  - task: PowerShell@2
    displayName: git status
    condition: always()
    inputs:
      targetType: inline
      script: |
        # Write your PowerShell commands here.
        $params = '$(params)' | ConvertFrom-Json
        Write-Host $params.target_repo.repo_root
        Push-Location $params.target_repo.repo_root
        $configPath = Join-Path $params.target_repo.repo_root 'ci-configs'
        Write-Host $configPath
        ls
        git status
      pwsh: true
  - task: AzurePowerShell@5
    displayName: git push
    inputs:
      azureSubscription: 631c8994-cbef-48c4-b7f2-d97e8a790c29 # ReferenceAutomationPipeline
      ScriptPath: common/CI.push.ps1
      ScriptArguments: -paramsJson '$(params)' -vstsTokenBase64 '$(vstsTokenBase64)'
      FailOnStandardError: true
      azurePowerShellVersion: LatestVersion